#!/bin/bash
################
#BH1
M1=10.0
S1=-1.4E+02
THETA1=60.0
PHI1=0.0
A1=0.9
################
#BH2
M2=10.0
S2=-1.4E+02
THETA2=-60.0
PHI2=0.0
A2=0.9
################
#
echo "$M1 $M2 $S1 $THETA1 $PHI1 $S2 $THETA2 $PHI2 $A1 $A2" | ./gwkik2
